# parameters for CNV/window size calculations defaults from HLiang:
# https://github.com/hliang/cnv-seq
parameters:
  annotate: TRUE
  bed_file_present: FALSE
  bigger: 1.5
  log2: 0.6
  pvalue: 0.001
  window_size: 10000

# list of chromosomes to be analyzed
chromosomes: 
#   - Chr01
#   - Chr02
#   - Chr03
#   - Chr04
#   - Chr05
#   - Chr06
  - Chr07
  - Chr08
  - Chr09
#   - Chr10

# folder to store outputs; should be inside "output" directory, example:
# output_path: output/run-name or output/organism
output_path: output/sorghum-example

# path to bed file for varying window sizes (optional)
bed_path: 

# paths to bam files
paths:
  con: &con /home/anibal/bam_files/sorghum/1con_sample_all-chroms.bam
  D2: &D2 /home/anibal/bam_files/sorghum/1D2_sample_all-chroms.bam
  D3: &D3 /home/anibal/bam_files/sorghum/1D3_sample_all-chroms.bam

# comparisons to be analyzed
comparisons:
  comparison_1:
    control: *con
    mutant: *D2
  2_mutants_comp:
   control: *D2
   mutant: *D3
  another_comparison:
    control: *con
    mutant: *D3
